import { renderProductCards } from "/src/components/ui/product-card-list.js";

const productDataList = [
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 30ml",
    badgeType: "NEW",
    size: "30 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 17000,
    discountRate: 50,
    discountPrice: 8500,
    isWished: true,
  },
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 75ml",
    badgeType: "NEW",
    size: "75 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 29000,
    discountRate: null,
    discountPrice: null,
    isWished: false,
  },
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 150ml",
    badgeType: "NEW",
    size: "150 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 42000,
    discountRate: null,
    discountPrice: null,
    isWished: false,
  },
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 150ml",
    badgeType: "NEW",
    size: "150 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 42000,
    discountRate: null,
    discountPrice: null,
    isWished: false,
  },
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 150ml",
    badgeType: "NEW",
    size: "150 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 42000,
    discountRate: null,
    discountPrice: null,
    isWished: false,
  },
  {
    image: "/src/assets/images/product1_0.webp",
    imageAlt: "시어 버터 핸드 크림 150ml",
    badgeType: "NEW",
    size: "150 ml",
    name: "시어 버터 핸드 크림 (카리테 콩포르)",
    originalPrice: 42000,
    discountRate: null,
    discountPrice: null,
    isWished: false,
  },
];

renderProductCards(productDataList);
